Added Mac compatibility
This bundled fzf thing is a bit untenable for more versions, but I
need fzf to upgrade to 0.40.0 before I can remove it. Even then, it'll
be tricky on some devices where fzf isn't typically installed, like
Macs.

diff --git a/purr b/purr
--- a/purr
+++ b/purr
@@ -20,6 +20,10 @@
 # 60-69: Irrecoverable ADB-related error.
 #   61 - Could not get a serial number.
 
+timeout() {
+    perl -e 'alarm shift; exec @ARGV' "$@"
+}
+
 # Queries the user to choose between all connected adb devices.
 # Output: Serial number of the chosen adb device, to be used in adb -s $(pick_serial).
 pick_serial() {
@@ -64,10 +68,10 @@ pick_serial() {
         local stripped_device=$(echo "$adb_devices" | xargs)
     else
         if command -v rg &>/dev/null; then
-            local stripped_device=$(FZF_DEFAULT_COMMAND="echo \"$adb_devices\"" fzf_purr $fzfpnh "--height=25%" --preview-window=right,50%,wrap \
-                "--preview=adb -s \$(cut -f1 <<< {}) shell getprop | /usr/bin/rg '(ro.bootimage.build.date]|ro.product.name|ro.bootimage.build.version.incremental])' | awk -F ']:' '{print \$2}' | sed 's/]//g' | sed 's/\[//g' " | xargs)
+            local stripped_device=$(FZF_DEFAULT_COMMAND="echo \"$adb_devices\"" $fzf_purr $fzfpnh "--height=25%" --preview-window=right,50%,wrap \
+                "--preview=adb -s \$(cut -f1 <<< {}) shell getprop | rg '(ro.bootimage.build.date]|ro.product.name|ro.bootimage.build.version.incremental])' | awk -F ']:' '{print \$2}' | sed 's/]//g' | sed 's/\[//g' " | xargs)
         else
-            local stripped_device=$(FZF_DEFAULT_COMMAND="echo \"$adb_devices\"" fzf_purr $fzfpnh "--height=25%" | xargs)
+            local stripped_device=$(FZF_DEFAULT_COMMAND="echo \"$adb_devices\"" $fzf_purr $fzfpnh "--height=25%" | xargs)
         fi
     fi
 
@@ -86,13 +90,15 @@ __pick_serial_wait() {
 
     # See if any devices are immediately connected before printing a connect message.
     if [ -z $serial ]; then
-        /usr/bin/timeout 0.2 adb wait-for-device 2> /dev/null
+        timeout 1 "adb wait-for-device" 2> /dev/null
+        ret=$?
     else
-        /usr/bin/timeout 0.2 adb -s $serial wait-for-device 2> /dev/null
+        timeout 1 "adb -s $serial wait-for-device" 2> /dev/null
+        ret=$?
     fi
     
     # If we can't find any immediate connections, go into a longer waiting period.
-    if [ $? -eq 124 ]; then
+    if [ $ret -eq 124 ] || [ $ret -eq 142 ]; then
         if [ -z $serial ]; then
             echo "Waiting on a device to connect..." > /dev/tty
             adb wait-for-device
@@ -271,7 +277,7 @@ __purr_cleanup() {
 
     # Delete all of the cached state files.
     if [ -d $dir_name ]; then
-        /usr/bin/rm -r $dir_name
+        rm -r $dir_name
     fi
 }
 
@@ -309,10 +315,10 @@ __purr_start_streams() {
 __purr_cleanup_streams() {
     kill ${${(v)jobstates##*:*:}%=*}
     sleep 0.5
-    /usr/bin/rm $purr_error_input_cache &> /dev/null
-    /usr/bin/rm $purr_warning_input_cache &> /dev/null
-    /usr/bin/rm $purr_info_input_cache &> /dev/null
-    /usr/bin/rm $purr_verbose_input_cache &> /dev/null
+    rm $purr_error_input_cache &> /dev/null
+    rm $purr_warning_input_cache &> /dev/null
+    rm $purr_info_input_cache &> /dev/null
+    rm $purr_verbose_input_cache &> /dev/null
 }
 
 # The function that runs the stream threads. Each should run an
@@ -351,7 +357,7 @@ __purr_stream_background_file() {
 
         # If we disconnected, we want to make sure that the device is still offline.
         if [[ $conn_status = "potential" ]]; then
-            /usr/bin/timeout 2 adb -s $serial wait-for-device &> /dev/null
+            timeout 2 "adb -s $serial wait-for-device" &> /dev/null
 
             # The device seems to have found itself, we can just reconnect.
             if [ $? -eq 0 ]; then
@@ -425,8 +431,31 @@ usage=("purr"
     "\n[-f: Set custom fzf parameters as a string]"
     "\n[-v: Get version number]")
 
-VERSION="1.0.1"
-COMPOSITE_VERSION="Purr: $VERSION, fzf: $(fzf_purr --version), zsh: $ZSH_VERSION"
+# Load the correct version of purr. We won't need this once fzf releases 0.40.0
+# to the applicable places. For now, we sideload fzf. Otherwise, we load the 
+# local fzf binary. Why these specific versions? Because this is an internal tool.
+autoload is-at-least
+if command -v rg &> /dev/null && is-at-least "0.40.0" $(fzf --version | cut -d' ' -f1); then
+    fzf_purr="fzf"
+elif [ $(uname -s) = "Darwin" ]; then
+    if [ $(arch) = "arm64" ]; then
+        fzf_purr="purr_fzf_darwin_arm64"
+    elif [ $(arch) = "i386" ]; then
+        fzf_purr="purr_fzf_darwin_amd64"
+    fi
+elif [ $(uname -s) = "Linux" ]; then
+    if [ $(arch) = "x86_64" ]; then
+        fzf_purr="purr_fzf_linux_x86_64"
+    fi
+fi
+
+if [ -z $fzf_purr ]; then
+    echo "Could not identify valid fzf version."
+    echo "purr requires fzf 0.40.0 or higher."
+fi
+
+VERSION="1.0.2"
+COMPOSITE_VERSION="Purr: $VERSION, fzf: $($fzf_purr --version), zsh: $ZSH_VERSION"
 
 # Parse argument flags.
 instruction_flag=true
@@ -449,10 +478,10 @@ if ! __purr_check_env; then
 fi
 
 # Create the directory our cache file will live.
-rand_prefix=$(/usr/bin/cat /dev/urandom | /usr/bin/tr -cd 'a-f0-9' | /usr/bin/head -c 8)
-cur_time=$(($(/usr/bin/date +%s) * 1000))
+rand_prefix=$(cat /dev/urandom | LC_ALL=C /usr/bin/tr -cd 'a-f0-9' | /usr/bin/head -c 8)
+cur_time=$(($(date +%s) * 1000))
 dir_name="/tmp/purr_${rand_prefix}_${cur_time}"
-/usr/bin/mkdir "$dir_name"
+mkdir "$dir_name"
 
 # Makes sure that we'll always run the cleanup if we exit
 # abnormally, through ctrl-c for example.
@@ -819,8 +848,6 @@ cmd_sort=(
                 $set_sort_chrono
             "fi"
         '} &'
-    ')+reload('
-        $load_input_stream
     ")+transform-header("
         $load_generic_header
     ")+$default_command_suite"
@@ -920,7 +947,7 @@ history_input=(
             "cur_counter=\$(cat $purr_history_counter_cache);"
             'if [ $seen_counter -eq $cur_counter ]; then'
                 'query={q};'
-                "query=\$(echo \"\$query\" | xargs -d ' ' | tr -s ' ');"
+                "query=\$(echo \"\$query\" | xargs | tr -s ' ');"
                 'if [ -z "$query" ]; then'
                     ':;'
                 "elif /usr/bin/grep -cim1 -x \" *\$query *\" $purr_history_cache; then"
@@ -1129,10 +1156,10 @@ EOF
 
     # Starts and runs the actual fzf process.
     if [ ! -z $cached_query ]; then
-        accepted=$(FZF_DEFAULT_COMMAND="$defcmd" fzf_purr $instruction_preview $fzfp $fzf_prompt $bind_commands $start_command --query=$cached_query)
+        accepted=$(FZF_DEFAULT_COMMAND="$defcmd" $fzf_purr $instruction_preview $fzfp $fzf_prompt $bind_commands $start_command --query=$cached_query)
         ret=$?
     else
-        accepted=$(FZF_DEFAULT_COMMAND="$defcmd" fzf_purr $instruction_preview $fzfp $fzf_prompt $bind_commands $start_command)
+        accepted=$(FZF_DEFAULT_COMMAND="$defcmd" $fzf_purr $instruction_preview $fzfp $fzf_prompt $bind_commands $start_command)
         ret=$?
     fi
 
@@ -1184,7 +1211,7 @@ EOF
         # Grab the context around the accepted line.
         if [ $(echo $accepted | wc -l) -eq 1 ]; then
             if command -v rg &> /dev/null; then
-                /usr/bin/rg --color=always -F "$accepted" $purr_input_cache -C 500 > $purr_editor_input_cache
+                rg --color=always -F "$accepted" $purr_input_cache -C 500 > $purr_editor_input_cache
             else 
                 /usr/bin/grep --color=always -F "$accepted" $purr_input_cache -C 500 > $purr_editor_input_cache
             fi
